apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 10
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: project-container
    spec:
      containers:
      - name: project-container
        image: noamshmueli/projectimage:latest
        ports:
        - containerPort: 8080
  