apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: project-container
  template:
    metadata:
      labels:
        app: project-container
    spec:
      containers:
      - name: project-container
        image: noamshmueli/projectimage:latest
        ports:
        - containerPort: 5000
  
