apiVersion: v1
kind: Service
metadata:
  name: project-service
  labels:
    app: project-app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30036
    protocol: TCP
  selector:
        app: project-container    
